apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker-pod
  name: worker-pod
spec:
  containers:
  - image: ghcr.io/jitesoft/nginx:1.27.1
    #  - image: nginx:1.27.0
    name: worker-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: worker
status: {}
