apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: default
spec:
  selector:
    ssh-app: sshd
  ports:
    - protocol: TCP
      port: 22        # 服务暴露的端口
      targetPort: 22   # Pod 内的目标端口
      nodePort: 30022  # 暴露到 Node 上的端口
  type: NodePort

