# nginx-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service   # Service 名称
spec:
  type: NodePort                 # 指定类型为 NodePort
  selector:
    app: nginx                   # 匹配 Pod 的标签
  ports:
    - protocol: TCP
      port: 80                   # Service 监听的端口（集群内部访问端口）
      targetPort: 80             # Pod 的端口（与容器暴露的端口一致）
      nodePort: 30080            # 可选：手动指定节点端口（默认范围 30000-32767）
