---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  labels:
    app: redis
spec:
  #serviceName: redis-svc
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: registry.paas/cmss/redis:6.2.4
        command: ["sh", "-c"]
        args:
          - |
            redis-server --requirepass "" &
            sleep 5
            redis-cli SET hello "world"
            wait
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - name: redis-tcp
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30079

