apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
  namespace: default
spec:
  selector:
    app: nginx-test
  type: ClusterIP
  # type: NodePort
  # ClusterIP: None
  ports:
    - name: nginx-tcp
      protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30080 # 30000-32767
