# keepalived-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config
data:
  keepalived.conf.template: |
    vrrp_instance VI_1 {
        state BACKUP                # 初始状态设为 BACKUP，由优先级决定 Master
        #interface enp0s5            # TODO 
        priority ${PRIORITY}        # 环境变量动态注入
        virtual_router_id 51        # 集群内唯一 ID，所有节点相同
        #advert_int 1
        #authentication {
        #    auth_type PASS
        #    auth_pass 1234         # 集群内一致
        #}
        virtual_ipaddress {
            10.211.55.4/24        # 虚拟 IP（VIP）
        }
    }
